package com.generalbytes.batm.server.extensions.travelrule;

/**
 * Represents an event triggered by the CAS server when a travel rule transfer has been resolved.
 * This event provides details about the resolution of the transfer, including its identifiers and status.
 */
public interface ITravelRuleTransferResolvedEvent {

    /**
     * Retrieves the public identifier associated with a transfer. Generated by the CAS server.
     *
     * @return The public identifier of the transfer.
     */
    String getTransferPublicId();

    /**
     * Retrieves the external identifier associated with a transfer. Generated by a travel rule provider
     *
     * @return The external identifier of the transfer.
     */
    String getTransferExternalId();

    /**
     * Retrieves the resolved status of the transfer as determined by the CAS server.
     *
     * @return The status of the resolved transfer. Possible values are:
     * <ul>
     * <li>{@code APPROVED} - The transfer has been approved, ready to receive funds.</li>
     * <li>{@code REJECTED} - The transfer has been rejected, don't send funds</li>
     * <li>{@code IN_PROGRESS} - won't be used, only APPROVED/REJECTED values are allowed</li>
     * </ul>
     */
    TravelRuleProviderTransferStatus getResolvedStatus();
}
