/*************************************************************************************
 * Copyright (C) 2014-2025 GENERAL BYTES s.r.o. All rights reserved.
 *
 * This software may be distributed and modified under the terms of the GNU
 * General Public License version 2 (GPL2) as published by the Free Software
 * Foundation and appearing in the file GPL2.TXT included in the packaging of
 * this file. Please note that GPL2 Section 2[b] requires that all works based
 * on this software must also be made publicly available under the terms of
 * the GPL2 ("Copyleft").
 *
 * Contact information
 * -------------------
 *
 * GENERAL BYTES s.r.o.
 * Web      :  http://www.generalbytes.com
 *
 ************************************************************************************/
package com.generalbytes.batm.server.extensions.travelrule;

/**
 * Request to update a transfer at a travel rule provider.
 *
 * @see ITravelRuleProvider#updateTransfer(ITravelRuleTransferUpdateRequest)
 */
public interface ITravelRuleTransferUpdateRequest {

    /**
     * Get the id of the transfer to update.
     *
     * <p>This is the id generated by the provider at transfer creation.</p>
     *
     * @return The id.
     * @see ITravelRuleTransferInfo#getId()
     */
    String getId();

    /**
     * Get the public ID of the transfer to update.
     *
     * <p>This is the ID generated by the BATM server at transfer creation.</p>
     *
     * @return The public ID.
     * @see ITravelRuleTransferData#getPublicId()
     */
    String getPublicId();

    /**
     * Get the new transaction hash that the transfer should be updated with.
     *
     * @return The new transaction hash of the transfer.
     */
    String getTransactionHash();

}
