/*************************************************************************************
 * Copyright (C) 2014-2024 GENERAL BYTES s.r.o. All rights reserved.
 *
 * This software may be distributed and modified under the terms of the GNU
 * General Public License version 2 (GPL2) as published by the Free Software
 * Foundation and appearing in the file GPL2.TXT included in the packaging of
 * this file. Please note that GPL2 Section 2[b] requires that all works based
 * on this software must also be made publicly available under the terms of
 * the GPL2 ("Copyleft").
 *
 * Contact information
 * -------------------
 *
 * GENERAL BYTES s.r.o.
 * Web      :  http://www.generalbytes.com
 *
 ************************************************************************************/
package com.generalbytes.batm.server.extensions;

import java.util.Set;

public interface IReceiptDetails {

    String CUSTOM_DATA_RECEIPT_LANGUAGE = "receipt.language";
    String CUSTOM_DATA_RECEIPT_CELLPHONE = "receipt.cellphone";
    String CUSTOM_DATA_RECEIPT_EMAIL = "receipt.email";

    /**
     * @return serial number of the terminal where the transaction was created
     */
    String getTerminalSerialNumber();

    /**
     * @return unique (in server scope) transaction id. It is generated by server.
     */
    String getRemoteTransactionId();

    /**
     *
     * @return user cellphone used to send the receipt to
     */
    String getCellphone();

    /**
     * @return user email used to send the receipt to
     */
    String getEmail();

    /**
     * @return user selected language on the terminal
     */
    String getUserLanguage();

    /**
     * @return Methods used to send the receipt.
     */
    Set<ReceiptTransferMethod> getTransferMethods();

}
