/*************************************************************************************
 * Copyright (C) 2014-2020 GENERAL BYTES s.r.o. All rights reserved.
 *
 * This software may be distributed and modified under the terms of the GNU
 * General Public License version 2 (GPL2) as published by the Free Software
 * Foundation and appearing in the file GPL2.TXT included in the packaging of
 * this file. Please note that GPL2 Section 2[b] requires that all works based
 * on this software must also be made publicly available under the terms of
 * the GPL2 ("Copyleft").
 *
 * Contact information
 * -------------------
 *
 * GENERAL BYTES s.r.o.
 * Web      :  http://www.generalbytes.com
 *
 ************************************************************************************/
package com.generalbytes.batm.server.extensions;

import java.math.BigDecimal;
import java.util.Map;

public interface ITransactionBuyInfo {
    /**
     * @return unique (in server scope) transaction id. It is generated by server.
     */
    String getRemoteTransactionId();

    /**
     * @return transaction id generated locally by terminal to perform request on server.
     * Don't use it if you don't have to. It is used only for time before server assigns remote transaction id to a transaction.
     */
    String getLocalTransactionId();

    /**
     * @return status of the transaction
     * @see ITransactionDetails
     */
    int getStatus();

    /**
     * @return Fiat amount
     */
    BigDecimal getCashAmount();

    /**
     * @return Fiat currency code (USD, EUR etc)
     */
    String getCashCurrency();

    /**
     * @return Cryptocurrency amount
     */
    BigDecimal getCryptoAmount();

    /**
     * @return cryptocurrency code (e.g. BTC, LTC, ...)
     */
    String getCryptoCurrency();

    /**
     * @return destination cryptocurrency address
     */
    String getCryptoAddress();

    /**
     * @return Custom texts that should be written on the ticket. Custom data are usually generated by ITransactionListener
     */
    Map<String, String> getCustomData();
}
