package com.generalbytes.batm.server.extensions.travelrule.notabene.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Holds information about a transfer.
 *
 * <p>This is a part of the response by several endpoints
 * and webhook payloads.</p>
 */
@Getter
@Setter
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@ToString
public class NotabeneTransferInfo {

    /**
     * Identifier of the Transfer, generated by Notabene.
     */
    private String id;
    /**
     * Identifier of the Transfer, provided by server at create.
     */
    private String transactionRef;
    /**
     * Status of the Transfer.
     *
     * @see NotabeneTransferStatus
     */
    private NotabeneTransferStatus status;
    /**
     * Type of the Transfer.
     *
     * @see NotabeneTransferType
     */
    private NotabeneTransferType transactionType;
    /**
     * The type of the asset as Asset Symbol (BTC, ETH)
     */
    private String transactionAsset;
    /**
     * Amount in base unit of the asset (satoshi, wei, etc.)
     */
    private String transactionAmount;
    private int chargedQuantity;
    /**
     * Originator Decentralized Identifier.
     *
     * @see <a href="https://devx.notabene.id/docs/decentralized-identifiers-dids">Notabene Documentation</a>
     */
    private String originatorDid;
    /**
     * Beneficiary Decentralized Identifier.
     *
     * @see <a href="https://devx.notabene.id/docs/decentralized-identifiers-dids">Notabene Documentation</a>
     */
    private String beneficiaryDid;
    /**
     * Originator VASP Decentralized Identifier
     *
     * @see <a href="https://devx.notabene.id/docs/decentralized-identifiers-dids">Notabene Documentation</a>
     */
    @JsonProperty("originatorVASPdid")
    private String originatorVaspDid;
    /**
     * Beneficiary VASP Decentralized Identifier
     *
     * @see <a href="https://devx.notabene.id/docs/decentralized-identifiers-dids">Notabene Documentation</a>
     */
    @JsonProperty("beneficiaryVASPdid")
    private String beneficiaryVaspDid;
    /**
     * Information about the transaction on the blockchain.
     *
     * @see NotabeneTransactionBlockchainInfo
     */
    private NotabeneTransactionBlockchainInfo transactionBlockchainInfo;

}
