package com.generalbytes.batm.server.extensions.travelrule.gtr.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.generalbytes.batm.server.extensions.travelrule.gtr.api.GtrApi;
import com.generalbytes.batm.server.extensions.travelrule.gtr.util.RequestIdGenerator;
import lombok.Getter;
import lombok.Setter;

/**
 * Request object containing transaction ID (on-chain transaction hash).
 * Used in {@link GtrApi#notifyTxId(String, GtrNotifyTxIdRequest)}.
 */
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_DEFAULT)
public class GtrNotifyTxIdRequest {
    /**
     * Request ID generated by {@link RequestIdGenerator#generateRequestId()}.
     */
    private String requestId;
    /**
     * The on-chain transaction hash.
     */
    private String txId;
}
