package com.generalbytes.batm.server.extensions.travelrule.gtr.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.generalbytes.batm.server.extensions.travelrule.gtr.api.GtrApi;
import com.generalbytes.batm.server.extensions.travelrule.gtr.util.RequestIdGenerator;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

/**
 * Request object containing data for PII verification at GTR.
 * Used in {@link GtrApi#verifyPii(String, GtrVerifyPiiRequest)}.
 */
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_DEFAULT)
public class GtrVerifyPiiRequest {
    /**
     * Request ID generated by {@link RequestIdGenerator#generateRequestId()}.
     */
    private String requestId;
    /**
     * The blockchain transaction hash if it exists, otherwise {@code null}.
     */
    private String txId;
    /**
     * Public key of initiator VASP.
     */
    private String initiatorPublicKey;
    /**
     * Code of target VASP.
     */
    private String targetVaspCode;
    /**
     * Public key of target VASP.
     */
    private String targetVaspPublicKey;
    /**
     * <p>Encrypted payload containing sensitive PII structured according to the IVMS101-2020 specification.</p>
     *
     * <p>The data is encrypted using asymmetric cryptography based on the Curve25519 elliptic curve.</p>
     */
    private String encryptedPayload;
    /**
     * Specifies the PII (Personally Identifiable Information) format and its version. It is currently ivms101-2020.
     */
    private String piiSpecVersion;
    /**
     * Specifies the type of PII encryption method.
     * <p>1: Curve25519</p>
     */
    private int secretType;
    /**
     * Crypto amount in base unit.
     */
    private String amount;
    /**
     * Fiat amount (price for the total amount of cryptocurrencies).
     */
    private String fiatPrice;
    /**
     * Fiat currency name in ISO 4217 standard (for example, USD, EUR, CZK, etc.)
     */
    private String fiatName;
    /**
     * Indicates whether the legal threshold logic should be applied when processing the Travel Rule verification.
     *
     * <p>If set to {@code true}, personally identifiable information (PII) will only be shared or verified
     * if the transaction amount exceeds the jurisdiction-specific legal threshold (e.g., 1000 EUR or equivalent).</p>
     *
     * <p>If set to {@code false} (default), PII will be processed regardless of the transaction amount.</p>
     */
    private boolean lawThresholdEnabled;
    /**
     * Expected PII fields for counterparty verification.
     *
     * @see <a href="https://www.globaltravelrule.com/documentation/pii-verify-fields">Global Travel Rule (GTR) documentation</a>
     */
    private List<String> expectVerifyFields;
}
