package com.generalbytes.batm.server.extensions.travelrule.gtr.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.generalbytes.batm.server.extensions.travelrule.gtr.api.GtrApi;
import com.generalbytes.batm.server.extensions.travelrule.gtr.util.RequestIdGenerator;
import lombok.Getter;
import lombok.Setter;

/**
 * Request object containing data for address verification at GTR.
 * Used in {@link GtrApi#verifyAddress(String, GtrVerifyAddressRequest)}.
 */
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_DEFAULT)
public class GtrVerifyAddressRequest {
    /**
     * Request ID generated by {@link RequestIdGenerator#generateRequestId()}.
     */
    private String requestId;
    /**
     * The address to be verified.
     */
    private String address;
    /**
     * Destination tag used in some cryptocurrencies to identify a specific address, for example XRP (Ripple) or XLM (Stellar).
     * Optional parameter.
     */
    private String tag;
    /**
     * Public key of initiator VASP.
     */
    private String initiatorPublicKey;
    /**
     * Code of target VASP.
     */
    private String targetVaspCode;
    /**
     * Public key of target VASP.
     */
    private String targetVaspPublicKey;
    /**
     * The ticker of the cryptocurrency for which the address is to be verified.
     *
     * @see <a href="https://www.globaltravelrule.com/documentation/ticker-and-network-mapping">Global Travel Rule (GTR) documentation</a>
     */
    private String ticker;
    /**
     * The network on which the cryptocurrency operates.
     *
     * @see <a href="https://www.globaltravelrule.com/documentation/ticker-and-network-mapping">Global Travel Rule (GTR) documentation</a>
     */
    private String network;
}
