package com.generalbytes.batm.server.extensions.travelrule.gtr.api;

import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrVaspResponse;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrVerifyAddressResponse;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrLoginRequest;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrLoginResponse;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrNotifyTxIdRequest;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrNotifyTxIdResponse;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrRegisterTravelRuleRequest;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrRegisterTravelRuleResponse;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrVaspListResponse;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrVerifyAddressRequest;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrVerifyPiiRequest;
import com.generalbytes.batm.server.extensions.travelrule.gtr.dto.GtrVerifyPiiResponse;
import com.generalbytes.batm.server.extensions.travelrule.gtr.util.RequestIdGenerator;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;

/**
 * Provides access to relevant Global Travel Rule (GTR) endpoints.
 *
 * @see <a href="https://www.globaltravelrule.com/documentation/">Global Travel Rule (GTR) documentation</a>
 */
@Path("/api")
@Produces(MediaType.APPLICATION_JSON)
public interface GtrApi {

    String AUTHORIZATION_HEADER_NAME = "Authorization";

    /**
     * Generates and returns an JWT access token.
     *
     * @param request Request object containing data for generate JWT access token.
     * @return Response object with JWT access token.
     * @throws GtrApiException If the call fails.
     *
     * @see <a href="https://www.globaltravelrule.com/documentation/api-references/common-api/post-api-login">Global Travel Rule (GTR) documentation</a>
     */
    @POST
    @Path("/login")
    @Consumes(MediaType.APPLICATION_JSON)
    GtrLoginResponse login(GtrLoginRequest request) throws GtrApiException;

    /**
     * Get list of all VASPs.
     *
     * @param authorization The Authorization header content containing JWT token from {@link #login}.
     * @return Response object containing basic data about all VASPs.
     * @throws GtrApiException If the call fails.
     *
     * @see <a href="https://www.globaltravelrule.com/documentation/api-references/common-api/get-api-vasp-list">Global Travel Rule (GTR) documentation</a>
     */
    @GET
    @Path("/vasp/list")
    GtrVaspListResponse listVasps(@HeaderParam(AUTHORIZATION_HEADER_NAME) String authorization) throws GtrApiException;


    /**
     * Get detail about VASP.
     *
     * @param authorization The Authorization header content containing JWT token from {@link #login}.
     * @param vaspCode      VASP code.
     * @return Response object containing data about VASP.
     * @throws GtrApiException If the call fails.
     *
     * @see <a href="https://www.globaltravelrule.com/documentation/api-references/common-api/get-api-vasp-detail">Global Travel Rule (GTR) documentation</a>
     */
    @GET
    @Path("/vasp/detail")
    GtrVaspResponse vaspDetail(@HeaderParam(AUTHORIZATION_HEADER_NAME) String authorization,
                               @QueryParam("vaspCode") String vaspCode) throws GtrApiException;

    /**
     * Registers a new Travel Rule request.
     *
     * @param authorization The Authorization header content containing JWT token from {@link #login}.
     * @param request       Request object containing generated Request ID from {@link RequestIdGenerator}.
     * @return Response object containing Request ID and Travel Rule ID generated by the GTR server.
     * @throws GtrApiException If the call fails.
     *
     * @see <a href="https://www.globaltravelrule.com/documentation/api-references/standard-travel-rule-2-0-api/post-api-verify-v-2-register">Global Travel Rule (GTR) documentation</a>
     */
    @POST
    @Path("/verify/v2/register")
    @Consumes(MediaType.APPLICATION_JSON)
    GtrRegisterTravelRuleResponse registerTravelRuleRequest(@HeaderParam(AUTHORIZATION_HEADER_NAME) String authorization,
                                                            GtrRegisterTravelRuleRequest request) throws GtrApiException;

    /**
     * Verify address with GTR.
     *
     * @param authorization The Authorization header content containing JWT token from {@link #login}.
     * @param request       Request object containing data for address verification at GTR.
     * @return Response object containing data about the result of address verification.
     * @throws GtrApiException If the call fails.
     *
     * @see <a href="https://www.globaltravelrule.com/documentation/api-references/standard-travel-rule-2-0-api/post-api-verify-v-2-verify-address">Global Travel Rule (GTR) documentation</a>
     */
    @POST
    @Path("/verify/v2/verify_address")
    @Consumes(MediaType.APPLICATION_JSON)
    GtrVerifyAddressResponse verifyAddress(@HeaderParam(AUTHORIZATION_HEADER_NAME) String authorization,
                                           GtrVerifyAddressRequest request) throws GtrApiException;

    /**
     * Verify PII (Personally Identifiable Information) with GTR.
     *
     * @param authorization The Authorization header content containing JWT token from {@link #login}.
     * @param request       Request object containing data for PII verification at GTR.
     * @return Response object containing data about the result of PII verification.
     * @throws GtrApiException If the call fails.
     *
     * @see <a href="https://www.globaltravelrule.com/documentation/api-references/standard-travel-rule-2-0-api/post-api-verify-v-2-verify-pii">Global Travel Rule (GTR) documentation</a>
     */
    @POST
    @Path("/verify/v2/verify_pii")
    @Consumes(MediaType.APPLICATION_JSON)
    GtrVerifyPiiResponse verifyPii(@HeaderParam(AUTHORIZATION_HEADER_NAME) String authorization,
                                   GtrVerifyPiiRequest request) throws GtrApiException;

    /**
     * Notifies the beneficiary VASP via GTR about the on-chain transaction hash.
     *
     * @param authorization The Authorization header content containing JWT token from {@link #login}.
     * @param request       Request object containing on-chain transaction hash.
     * @return Response object containing the result of the on-chain transaction hash notification.
     * @throws GtrApiException If the call fails.
     *
     * @see <a href="https://www.globaltravelrule.com/documentation/api-references/standard-travel-rule-2-0-api/post-api-verify-v-2-notify-tx-id">Global Travel Rule (GTR) documentation</a>
     */
    @POST
    @Path("/verify/v2/notify_tx_id")
    @Consumes(MediaType.APPLICATION_JSON)
    GtrNotifyTxIdResponse notifyTxId(@HeaderParam(AUTHORIZATION_HEADER_NAME) String authorization,
                                     GtrNotifyTxIdRequest request) throws GtrApiException;

}
