//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 11:07:14 AM CET 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * The birthdate is a type that describes all that the system knows about the birthdate associated to a sanctioned entity.
 * 
 * <p>Java class for BirthdateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BirthdateType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eu.europa.ec/fpi/fsd/export}SanctionableType">
 *       &lt;attGroup ref="{http://eu.europa.ec/fpi/fsd/export}country"/>
 *       &lt;attribute name="circa" type="{http://eu.europa.ec/fpi/fsd/export}BooleanType" />
 *       &lt;attribute name="calendarType" use="required" type="{http://eu.europa.ec/fpi/fsd/export}CalendarTypeType" />
 *       &lt;attribute name="city" type="{http://eu.europa.ec/fpi/fsd/export}LargeDescriptionType" />
 *       &lt;attribute name="zipCode" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="birthdate" type="{http://eu.europa.ec/fpi/fsd/export}DateType" />
 *       &lt;attribute name="dayOfMonth" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="monthOfYear" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="year" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="yearRangeFrom" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="yearRangeTo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="region" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="place" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BirthdateType")
public class BirthdateType
    extends SanctionableType
{

    @XmlAttribute(name = "circa")
    protected Boolean circa;
    @XmlAttribute(name = "calendarType", required = true)
    protected CalendarTypeType calendarType;
    @XmlAttribute(name = "city")
    protected String city;
    @XmlAttribute(name = "zipCode")
    protected String zipCode;
    @XmlAttribute(name = "birthdate")
    protected XMLGregorianCalendar birthdate;
    @XmlAttribute(name = "dayOfMonth")
    protected Integer dayOfMonth;
    @XmlAttribute(name = "monthOfYear")
    protected Integer monthOfYear;
    @XmlAttribute(name = "year")
    protected Integer year;
    @XmlAttribute(name = "yearRangeFrom")
    protected Integer yearRangeFrom;
    @XmlAttribute(name = "yearRangeTo")
    protected Integer yearRangeTo;
    @XmlAttribute(name = "region")
    protected String region;
    @XmlAttribute(name = "place")
    protected String place;
    @XmlAttribute(name = "countryIso2Code", required = true)
    protected String countryIso2Code;
    @XmlAttribute(name = "countryDescription", required = true)
    protected String countryDescription;

    /**
     * Gets the value of the circa property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCirca() {
        return circa;
    }

    /**
     * Sets the value of the circa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCirca(Boolean value) {
        this.circa = value;
    }

    /**
     * Gets the value of the calendarType property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarTypeType }
     *     
     */
    public CalendarTypeType getCalendarType() {
        return calendarType;
    }

    /**
     * Sets the value of the calendarType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarTypeType }
     *     
     */
    public void setCalendarType(CalendarTypeType value) {
        this.calendarType = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the birthdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthdate() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthdate(XMLGregorianCalendar value) {
        this.birthdate = value;
    }

    /**
     * Gets the value of the dayOfMonth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDayOfMonth() {
        return dayOfMonth;
    }

    /**
     * Sets the value of the dayOfMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDayOfMonth(Integer value) {
        this.dayOfMonth = value;
    }

    /**
     * Gets the value of the monthOfYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMonthOfYear() {
        return monthOfYear;
    }

    /**
     * Sets the value of the monthOfYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMonthOfYear(Integer value) {
        this.monthOfYear = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYear(Integer value) {
        this.year = value;
    }

    /**
     * Gets the value of the yearRangeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYearRangeFrom() {
        return yearRangeFrom;
    }

    /**
     * Sets the value of the yearRangeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYearRangeFrom(Integer value) {
        this.yearRangeFrom = value;
    }

    /**
     * Gets the value of the yearRangeTo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYearRangeTo() {
        return yearRangeTo;
    }

    /**
     * Sets the value of the yearRangeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYearRangeTo(Integer value) {
        this.yearRangeTo = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlace(String value) {
        this.place = value;
    }

    /**
     * Gets the value of the countryIso2Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryIso2Code() {
        return countryIso2Code;
    }

    /**
     * Sets the value of the countryIso2Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryIso2Code(String value) {
        this.countryIso2Code = value;
    }

    /**
     * Gets the value of the countryDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryDescription() {
        return countryDescription;
    }

    /**
     * Sets the value of the countryDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryDescription(String value) {
        this.countryDescription = value;
    }

}
