//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 11:07:14 AM CET 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * The identification is a type that describes all that the system knows about the identification document associated to a sanctioned entity.
 * 
 * <p>Java class for IdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentificationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eu.europa.ec/fpi/fsd/export}SanctionableType">
 *       &lt;attGroup ref="{http://eu.europa.ec/fpi/fsd/export}identificationType"/>
 *       &lt;attGroup ref="{http://eu.europa.ec/fpi/fsd/export}country"/>
 *       &lt;attribute name="diplomatic" type="{http://eu.europa.ec/fpi/fsd/export}BooleanType" />
 *       &lt;attribute name="knownExpired" type="{http://eu.europa.ec/fpi/fsd/export}BooleanType" />
 *       &lt;attribute name="knownFalse" type="{http://eu.europa.ec/fpi/fsd/export}BooleanType" />
 *       &lt;attribute name="reportedLost" type="{http://eu.europa.ec/fpi/fsd/export}BooleanType" />
 *       &lt;attribute name="revokedByIssuer" type="{http://eu.europa.ec/fpi/fsd/export}BooleanType" />
 *       &lt;attribute name="issueDate" type="{http://eu.europa.ec/fpi/fsd/export}DateType" />
 *       &lt;attribute name="issuedBy" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="latinNumber" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="nameOnDocument" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="number" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="validFrom" type="{http://eu.europa.ec/fpi/fsd/export}DateType" />
 *       &lt;attribute name="validTo" type="{http://eu.europa.ec/fpi/fsd/export}DateType" />
 *       &lt;attribute name="region" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificationType")
public class IdentificationType
    extends SanctionableType
{

    @XmlAttribute(name = "diplomatic")
    protected Boolean diplomatic;
    @XmlAttribute(name = "knownExpired")
    protected Boolean knownExpired;
    @XmlAttribute(name = "knownFalse")
    protected Boolean knownFalse;
    @XmlAttribute(name = "reportedLost")
    protected Boolean reportedLost;
    @XmlAttribute(name = "revokedByIssuer")
    protected Boolean revokedByIssuer;
    @XmlAttribute(name = "issueDate")
    protected XMLGregorianCalendar issueDate;
    @XmlAttribute(name = "issuedBy")
    protected String issuedBy;
    @XmlAttribute(name = "latinNumber")
    protected String latinNumber;
    @XmlAttribute(name = "nameOnDocument")
    protected String nameOnDocument;
    @XmlAttribute(name = "number")
    protected String number;
    @XmlAttribute(name = "validFrom")
    protected XMLGregorianCalendar validFrom;
    @XmlAttribute(name = "validTo")
    protected XMLGregorianCalendar validTo;
    @XmlAttribute(name = "region")
    protected String region;
    @XmlAttribute(name = "identificationTypeCode", required = true)
    protected String identificationTypeCode;
    @XmlAttribute(name = "identificationTypeDescription", required = true)
    protected String identificationTypeDescription;
    @XmlAttribute(name = "countryIso2Code", required = true)
    protected String countryIso2Code;
    @XmlAttribute(name = "countryDescription", required = true)
    protected String countryDescription;

    /**
     * Gets the value of the diplomatic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDiplomatic() {
        return diplomatic;
    }

    /**
     * Sets the value of the diplomatic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDiplomatic(Boolean value) {
        this.diplomatic = value;
    }

    /**
     * Gets the value of the knownExpired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKnownExpired() {
        return knownExpired;
    }

    /**
     * Sets the value of the knownExpired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKnownExpired(Boolean value) {
        this.knownExpired = value;
    }

    /**
     * Gets the value of the knownFalse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKnownFalse() {
        return knownFalse;
    }

    /**
     * Sets the value of the knownFalse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKnownFalse(Boolean value) {
        this.knownFalse = value;
    }

    /**
     * Gets the value of the reportedLost property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReportedLost() {
        return reportedLost;
    }

    /**
     * Sets the value of the reportedLost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReportedLost(Boolean value) {
        this.reportedLost = value;
    }

    /**
     * Gets the value of the revokedByIssuer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRevokedByIssuer() {
        return revokedByIssuer;
    }

    /**
     * Sets the value of the revokedByIssuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRevokedByIssuer(Boolean value) {
        this.revokedByIssuer = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDate(XMLGregorianCalendar value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the issuedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuedBy() {
        return issuedBy;
    }

    /**
     * Sets the value of the issuedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuedBy(String value) {
        this.issuedBy = value;
    }

    /**
     * Gets the value of the latinNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatinNumber() {
        return latinNumber;
    }

    /**
     * Sets the value of the latinNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatinNumber(String value) {
        this.latinNumber = value;
    }

    /**
     * Gets the value of the nameOnDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOnDocument() {
        return nameOnDocument;
    }

    /**
     * Sets the value of the nameOnDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOnDocument(String value) {
        this.nameOnDocument = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the identificationTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificationTypeCode() {
        return identificationTypeCode;
    }

    /**
     * Sets the value of the identificationTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificationTypeCode(String value) {
        this.identificationTypeCode = value;
    }

    /**
     * Gets the value of the identificationTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificationTypeDescription() {
        return identificationTypeDescription;
    }

    /**
     * Sets the value of the identificationTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificationTypeDescription(String value) {
        this.identificationTypeDescription = value;
    }

    /**
     * Gets the value of the countryIso2Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryIso2Code() {
        return countryIso2Code;
    }

    /**
     * Sets the value of the countryIso2Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryIso2Code(String value) {
        this.countryIso2Code = value;
    }

    /**
     * Gets the value of the countryDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryDescription() {
        return countryDescription;
    }

    /**
     * Sets the value of the countryDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryDescription(String value) {
        this.countryDescription = value;
    }

}
