//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 11:07:14 AM CET 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * The name alias is a type that describes all that the system knows about the name associated to a sanctioned entity.
 * 			The nameLanguage, if present, might be different than the regulationLanguage if the name is expressed in another language than the one of the regulation.
 * 			The strong flag means that the current name alias is the main on for the sanctioned entity.
 * 
 * <p>Java class for NameAliasType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NameAliasType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eu.europa.ec/fpi/fsd/export}SanctionableType">
 *       &lt;attribute name="firstName" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="middleName" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="lastName" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="wholeName" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="function" type="{http://eu.europa.ec/fpi/fsd/export}LargeDescriptionType" />
 *       &lt;attribute name="gender" type="{http://eu.europa.ec/fpi/fsd/export}GenderType" />
 *       &lt;attribute name="title" type="{http://eu.europa.ec/fpi/fsd/export}LargeDescriptionType" />
 *       &lt;attribute name="nameLanguage" type="{http://eu.europa.ec/fpi/fsd/export}LanguageCodeType" />
 *       &lt;attribute name="strong" type="{http://eu.europa.ec/fpi/fsd/export}BooleanType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameAliasType")
public class NameAliasType
    extends SanctionableType
{

    @XmlAttribute(name = "firstName")
    protected String firstName;
    @XmlAttribute(name = "middleName")
    protected String middleName;
    @XmlAttribute(name = "lastName")
    protected String lastName;
    @XmlAttribute(name = "wholeName")
    protected String wholeName;
    @XmlAttribute(name = "function")
    protected String function;
    @XmlAttribute(name = "gender")
    protected String gender;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "nameLanguage")
    protected String nameLanguage;
    @XmlAttribute(name = "strong")
    protected Boolean strong;

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the wholeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWholeName() {
        return wholeName;
    }

    /**
     * Sets the value of the wholeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWholeName(String value) {
        this.wholeName = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunction(String value) {
        this.function = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the nameLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLanguage() {
        return nameLanguage;
    }

    /**
     * Sets the value of the nameLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLanguage(String value) {
        this.nameLanguage = value;
    }

    /**
     * Gets the value of the strong property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStrong() {
        return strong;
    }

    /**
     * Sets the value of the strong property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStrong(Boolean value) {
        this.strong = value;
    }

}
