//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 11:07:14 AM CET 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Export_QNAME = new QName("http://eu.europa.ec/fpi/fsd/export", "export");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExportType }
     * 
     */
    public ExportType createExportType() {
        return new ExportType();
    }

    /**
     * Create an instance of {@link ContactInfoType }
     * 
     */
    public ContactInfoType createContactInfoType() {
        return new ContactInfoType();
    }

    /**
     * Create an instance of {@link BirthdateType }
     * 
     */
    public BirthdateType createBirthdateType() {
        return new BirthdateType();
    }

    /**
     * Create an instance of {@link RegulationSummaryType }
     * 
     */
    public RegulationSummaryType createRegulationSummaryType() {
        return new RegulationSummaryType();
    }

    /**
     * Create an instance of {@link NameAliasType }
     * 
     */
    public NameAliasType createNameAliasType() {
        return new NameAliasType();
    }

    /**
     * Create an instance of {@link RegulationType }
     * 
     */
    public RegulationType createRegulationType() {
        return new RegulationType();
    }

    /**
     * Create an instance of {@link AdditionalInfoType }
     * 
     */
    public AdditionalInfoType createAdditionalInfoType() {
        return new AdditionalInfoType();
    }

    /**
     * Create an instance of {@link SubjectTypeType }
     * 
     */
    public SubjectTypeType createSubjectTypeType() {
        return new SubjectTypeType();
    }

    /**
     * Create an instance of {@link IdentificationType }
     * 
     */
    public IdentificationType createIdentificationType() {
        return new IdentificationType();
    }

    /**
     * Create an instance of {@link SanctionEntityType }
     * 
     */
    public SanctionEntityType createSanctionEntityType() {
        return new SanctionEntityType();
    }

    /**
     * Create an instance of {@link CitizenshipType }
     * 
     */
    public CitizenshipType createCitizenshipType() {
        return new CitizenshipType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eu.europa.ec/fpi/fsd/export", name = "export")
    public JAXBElement<ExportType> createExport(ExportType value) {
        return new JAXBElement<ExportType>(_Export_QNAME, ExportType.class, null, value);
    }

}
