//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 11:07:14 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://eu.europa.ec/fpi/fsd/export", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags;
