//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 11:07:14 AM CET 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * The regulation is a type that describes the information related to an official publication.
 * 
 * <p>Java class for RegulationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegulationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eu.europa.ec/fpi/fsd/export}OperableType">
 *       &lt;sequence>
 *         &lt;element name="publicationUrl" type="{http://eu.europa.ec/fpi/fsd/export}DefaultUrlType" minOccurs="0"/>
 *         &lt;element name="corrigendum" type="{http://eu.europa.ec/fpi/fsd/export}RegulationSummaryType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="regulationType" use="required" type="{http://eu.europa.ec/fpi/fsd/export}DefaultCodeType" />
 *       &lt;attribute name="organisationType" use="required" type="{http://eu.europa.ec/fpi/fsd/export}DefaultCodeType" />
 *       &lt;attribute name="publicationDate" use="required" type="{http://eu.europa.ec/fpi/fsd/export}DateType" />
 *       &lt;attribute name="entryIntoForceDate" use="required" type="{http://eu.europa.ec/fpi/fsd/export}DateType" />
 *       &lt;attribute name="numberTitle" use="required" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="programme" use="required" type="{http://eu.europa.ec/fpi/fsd/export}DefaultCodeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegulationType", propOrder = {
    "publicationUrl",
    "corrigendum"
})
public class RegulationType
    extends OperableType
{

    protected String publicationUrl;
    protected List<RegulationSummaryType> corrigendum;
    @XmlAttribute(name = "regulationType", required = true)
    protected String regulationType;
    @XmlAttribute(name = "organisationType", required = true)
    protected String organisationType;
    @XmlAttribute(name = "publicationDate", required = true)
    protected XMLGregorianCalendar publicationDate;
    @XmlAttribute(name = "entryIntoForceDate", required = true)
    protected XMLGregorianCalendar entryIntoForceDate;
    @XmlAttribute(name = "numberTitle", required = true)
    protected String numberTitle;
    @XmlAttribute(name = "programme", required = true)
    protected String programme;

    /**
     * Gets the value of the publicationUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationUrl() {
        return publicationUrl;
    }

    /**
     * Sets the value of the publicationUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationUrl(String value) {
        this.publicationUrl = value;
    }

    /**
     * Gets the value of the corrigendum property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the corrigendum property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCorrigendum().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegulationSummaryType }
     * 
     * 
     */
    public List<RegulationSummaryType> getCorrigendum() {
        if (corrigendum == null) {
            corrigendum = new ArrayList<RegulationSummaryType>();
        }
        return this.corrigendum;
    }

    /**
     * Gets the value of the regulationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulationType() {
        return regulationType;
    }

    /**
     * Sets the value of the regulationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulationType(String value) {
        this.regulationType = value;
    }

    /**
     * Gets the value of the organisationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisationType() {
        return organisationType;
    }

    /**
     * Sets the value of the organisationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisationType(String value) {
        this.organisationType = value;
    }

    /**
     * Gets the value of the publicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublicationDate(XMLGregorianCalendar value) {
        this.publicationDate = value;
    }

    /**
     * Gets the value of the entryIntoForceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEntryIntoForceDate() {
        return entryIntoForceDate;
    }

    /**
     * Sets the value of the entryIntoForceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEntryIntoForceDate(XMLGregorianCalendar value) {
        this.entryIntoForceDate = value;
    }

    /**
     * Gets the value of the numberTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberTitle() {
        return numberTitle;
    }

    /**
     * Sets the value of the numberTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberTitle(String value) {
        this.numberTitle = value;
    }

    /**
     * Gets the value of the programme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramme() {
        return programme;
    }

    /**
     * Sets the value of the programme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramme(String value) {
        this.programme = value;
    }

}
