//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 11:07:14 AM CET 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * The regulation summary is a type that contains the main information about a regulation.
 * 
 * <p>Java class for RegulationSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegulationSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="regulationType" use="required" type="{http://eu.europa.ec/fpi/fsd/export}DefaultCodeType" />
 *       &lt;attribute name="publicationDate" use="required" type="{http://eu.europa.ec/fpi/fsd/export}DateType" />
 *       &lt;attribute name="numberTitle" use="required" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="publicationUrl" type="{http://eu.europa.ec/fpi/fsd/export}DefaultUrlType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegulationSummaryType")
public class RegulationSummaryType {

    @XmlAttribute(name = "regulationType", required = true)
    protected String regulationType;
    @XmlAttribute(name = "publicationDate", required = true)
    protected XMLGregorianCalendar publicationDate;
    @XmlAttribute(name = "numberTitle", required = true)
    protected String numberTitle;
    @XmlAttribute(name = "publicationUrl")
    protected String publicationUrl;

    /**
     * Gets the value of the regulationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulationType() {
        return regulationType;
    }

    /**
     * Sets the value of the regulationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulationType(String value) {
        this.regulationType = value;
    }

    /**
     * Gets the value of the publicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublicationDate(XMLGregorianCalendar value) {
        this.publicationDate = value;
    }

    /**
     * Gets the value of the numberTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberTitle() {
        return numberTitle;
    }

    /**
     * Sets the value of the numberTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberTitle(String value) {
        this.numberTitle = value;
    }

    /**
     * Gets the value of the publicationUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicationUrl() {
        return publicationUrl;
    }

    /**
     * Sets the value of the publicationUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicationUrl(String value) {
        this.publicationUrl = value;
    }

}
