//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 11:07:14 AM CET 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * The sanction entity is a type that describes all that the system knows about an entity that is currently sanctioned.
 * 			The delisting date is the date from which the entity should not be sanctioned anymore for the regulation.
 * 			The designation date is the date of the first time the entity has been identified to be sanctioned.
 * 
 * <p>Java class for SanctionEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SanctionEntityType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eu.europa.ec/fpi/fsd/export}OperableType">
 *       &lt;sequence>
 *         &lt;element name="regulation" type="{http://eu.europa.ec/fpi/fsd/export}RegulationType"/>
 *         &lt;element name="subjectType" type="{http://eu.europa.ec/fpi/fsd/export}SubjectTypeType"/>
 *         &lt;element name="nameAlias" type="{http://eu.europa.ec/fpi/fsd/export}NameAliasType" maxOccurs="unbounded"/>
 *         &lt;element name="citizenship" type="{http://eu.europa.ec/fpi/fsd/export}CitizenshipType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="birthdate" type="{http://eu.europa.ec/fpi/fsd/export}BirthdateType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="address" type="{http://eu.europa.ec/fpi/fsd/export}AddressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="identification" type="{http://eu.europa.ec/fpi/fsd/export}IdentificationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="delistingDate" type="{http://eu.europa.ec/fpi/fsd/export}DateType" />
 *       &lt;attribute name="designationDate" type="{http://eu.europa.ec/fpi/fsd/export}DateType" />
 *       &lt;attribute name="designationDetails" type="{http://eu.europa.ec/fpi/fsd/export}UnlimitedTextType" />
 *       &lt;attribute name="unitedNationId" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *       &lt;attribute name="euReferenceNumber" type="{http://eu.europa.ec/fpi/fsd/export}DefaultDescriptionType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SanctionEntityType", propOrder = {
    "regulation",
    "subjectType",
    "nameAlias",
    "citizenship",
    "birthdate",
    "address",
    "identification"
})
public class SanctionEntityType
    extends OperableType
{

    @XmlElement(required = true)
    protected RegulationType regulation;
    @XmlElement(required = true)
    protected SubjectTypeType subjectType;
    @XmlElement(required = true)
    protected List<NameAliasType> nameAlias;
    protected List<CitizenshipType> citizenship;
    protected List<BirthdateType> birthdate;
    protected List<AddressType> address;
    protected List<IdentificationType> identification;
    @XmlAttribute(name = "delistingDate")
    protected XMLGregorianCalendar delistingDate;
    @XmlAttribute(name = "designationDate")
    protected XMLGregorianCalendar designationDate;
    @XmlAttribute(name = "designationDetails")
    protected String designationDetails;
    @XmlAttribute(name = "unitedNationId")
    protected String unitedNationId;
    @XmlAttribute(name = "euReferenceNumber")
    protected String euReferenceNumber;

    /**
     * Gets the value of the regulation property.
     * 
     * @return
     *     possible object is
     *     {@link RegulationType }
     *     
     */
    public RegulationType getRegulation() {
        return regulation;
    }

    /**
     * Sets the value of the regulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegulationType }
     *     
     */
    public void setRegulation(RegulationType value) {
        this.regulation = value;
    }

    /**
     * Gets the value of the subjectType property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectTypeType }
     *     
     */
    public SubjectTypeType getSubjectType() {
        return subjectType;
    }

    /**
     * Sets the value of the subjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectTypeType }
     *     
     */
    public void setSubjectType(SubjectTypeType value) {
        this.subjectType = value;
    }

    /**
     * Gets the value of the nameAlias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameAlias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameAlias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameAliasType }
     * 
     * 
     */
    public List<NameAliasType> getNameAlias() {
        if (nameAlias == null) {
            nameAlias = new ArrayList<NameAliasType>();
        }
        return this.nameAlias;
    }

    /**
     * Gets the value of the citizenship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citizenship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitizenship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CitizenshipType }
     * 
     * 
     */
    public List<CitizenshipType> getCitizenship() {
        if (citizenship == null) {
            citizenship = new ArrayList<CitizenshipType>();
        }
        return this.citizenship;
    }

    /**
     * Gets the value of the birthdate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the birthdate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBirthdate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BirthdateType }
     * 
     * 
     */
    public List<BirthdateType> getBirthdate() {
        if (birthdate == null) {
            birthdate = new ArrayList<BirthdateType>();
        }
        return this.birthdate;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressType }
     * 
     * 
     */
    public List<AddressType> getAddress() {
        if (address == null) {
            address = new ArrayList<AddressType>();
        }
        return this.address;
    }

    /**
     * Gets the value of the identification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getIdentification() {
        if (identification == null) {
            identification = new ArrayList<IdentificationType>();
        }
        return this.identification;
    }

    /**
     * Gets the value of the delistingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDelistingDate() {
        return delistingDate;
    }

    /**
     * Sets the value of the delistingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDelistingDate(XMLGregorianCalendar value) {
        this.delistingDate = value;
    }

    /**
     * Gets the value of the designationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDesignationDate() {
        return designationDate;
    }

    /**
     * Sets the value of the designationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDesignationDate(XMLGregorianCalendar value) {
        this.designationDate = value;
    }

    /**
     * Gets the value of the designationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignationDetails() {
        return designationDetails;
    }

    /**
     * Sets the value of the designationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignationDetails(String value) {
        this.designationDetails = value;
    }

    /**
     * Gets the value of the unitedNationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitedNationId() {
        return unitedNationId;
    }

    /**
     * Sets the value of the unitedNationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitedNationId(String value) {
        this.unitedNationId = value;
    }

    /**
     * Gets the value of the euReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEuReferenceNumber() {
        return euReferenceNumber;
    }

    /**
     * Sets the value of the euReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEuReferenceNumber(String value) {
        this.euReferenceNumber = value;
    }

}
