//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 11:07:14 AM CET 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.eu.tags;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * SanctionableType contains all the elements and attributes common to all the details of a sanction entity. This is an abstract type, so no element of this type will be present in the XML.
 * 
 * <p>Java class for SanctionableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SanctionableType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://eu.europa.ec/fpi/fsd/export}OperableType">
 *       &lt;sequence>
 *         &lt;element name="regulationSummary" type="{http://eu.europa.ec/fpi/fsd/export}RegulationSummaryType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="regulationLanguage" use="required" type="{http://eu.europa.ec/fpi/fsd/export}LanguageCodeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SanctionableType", propOrder = {
    "regulationSummary"
})
@XmlSeeAlso({
    BirthdateType.class,
    NameAliasType.class,
    IdentificationType.class,
    CitizenshipType.class,
    AddressType.class
})
public abstract class SanctionableType
    extends OperableType
{

    @XmlElement(required = true)
    protected RegulationSummaryType regulationSummary;
    @XmlAttribute(name = "regulationLanguage", required = true)
    protected String regulationLanguage;

    /**
     * Gets the value of the regulationSummary property.
     * 
     * @return
     *     possible object is
     *     {@link RegulationSummaryType }
     *     
     */
    public RegulationSummaryType getRegulationSummary() {
        return regulationSummary;
    }

    /**
     * Sets the value of the regulationSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegulationSummaryType }
     *     
     */
    public void setRegulationSummary(RegulationSummaryType value) {
        this.regulationSummary = value;
    }

    /**
     * Gets the value of the regulationLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulationLanguage() {
        return regulationLanguage;
    }

    /**
     * Sets the value of the regulationLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulationLanguage(String value) {
        this.regulationLanguage = value;
    }

}
