//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.17 at 11:26:16 AM CEST 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.ofac.tags;

import java.math.BigInteger;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}Comment" minOccurs="0"/>
 *         &lt;element name="Start" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DateBoundarySchemaType" minOccurs="0"/>
 *         &lt;element name="End" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DateBoundarySchemaType" minOccurs="0"/>
 *         &lt;element name="DurationMinimum" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DurationSchemaType" minOccurs="0"/>
 *         &lt;element name="DurationMaximum" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DurationSchemaType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CalendarTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="YearFixed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="MonthFixed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DayFixed" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comment",
    "start",
    "end",
    "durationMinimum",
    "durationMaximum"
})
@XmlRootElement(name = "DatePeriod", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class DatePeriod {

    @XmlElement(name = "Comment", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Comment comment;
    @XmlElement(name = "Start", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected DateBoundarySchemaType start;
    @XmlElement(name = "End", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected DateBoundarySchemaType end;
    @XmlElement(name = "DurationMinimum", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected DurationSchemaType durationMinimum;
    @XmlElement(name = "DurationMaximum", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected DurationSchemaType durationMaximum;
    @XmlAttribute(name = "CalendarTypeID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected BigInteger calendarTypeID;
    @XmlAttribute(name = "YearFixed", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected boolean yearFixed;
    @XmlAttribute(name = "MonthFixed", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected boolean monthFixed;
    @XmlAttribute(name = "DayFixed", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected boolean dayFixed;
    @XmlAttribute(name = "DeltaAction")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected DeltaActionSchemaType deltaAction;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link DateBoundarySchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public DateBoundarySchemaType getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateBoundarySchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setStart(DateBoundarySchemaType value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link DateBoundarySchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public DateBoundarySchemaType getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateBoundarySchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setEnd(DateBoundarySchemaType value) {
        this.end = value;
    }

    /**
     * Gets the value of the durationMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link DurationSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public DurationSchemaType getDurationMinimum() {
        return durationMinimum;
    }

    /**
     * Sets the value of the durationMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDurationMinimum(DurationSchemaType value) {
        this.durationMinimum = value;
    }

    /**
     * Gets the value of the durationMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link DurationSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public DurationSchemaType getDurationMaximum() {
        return durationMaximum;
    }

    /**
     * Sets the value of the durationMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDurationMaximum(DurationSchemaType value) {
        this.durationMaximum = value;
    }

    /**
     * Gets the value of the calendarTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public BigInteger getCalendarTypeID() {
        return calendarTypeID;
    }

    /**
     * Sets the value of the calendarTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setCalendarTypeID(BigInteger value) {
        this.calendarTypeID = value;
    }

    /**
     * Gets the value of the yearFixed property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isYearFixed() {
        return yearFixed;
    }

    /**
     * Sets the value of the yearFixed property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setYearFixed(boolean value) {
        this.yearFixed = value;
    }

    /**
     * Gets the value of the monthFixed property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isMonthFixed() {
        return monthFixed;
    }

    /**
     * Sets the value of the monthFixed property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setMonthFixed(boolean value) {
        this.monthFixed = value;
    }

    /**
     * Gets the value of the dayFixed property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public boolean isDayFixed() {
        return dayFixed;
    }

    /**
     * Sets the value of the dayFixed property.
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDayFixed(boolean value) {
        this.dayFixed = value;
    }

    /**
     * Gets the value of the deltaAction property.
     * 
     * @return
     *     possible object is
     *     {@link DeltaActionSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Sets the value of the deltaAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeltaActionSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDeltaAction(DeltaActionSchemaType value) {
        this.deltaAction = value;
    }

}
