//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.17 at 11:26:16 AM CEST 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.ofac.tags;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DistinctPartySchemaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistinctPartySchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}Comment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Profile" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}Comment" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Identity" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}IdentitySchemaType" maxOccurs="unbounded"/>
 *                   &lt;element name="Feature" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}FeatureSchemaType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="SanctionsEntryReference" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ExternalReference" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}Comment" minOccurs="0"/>
 *                             &lt;element name="ExRefValue" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DirectURL" minOccurs="0"/>
 *                             &lt;element name="SubLink" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Description" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DirectURL"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="TargetTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                                     &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="ExRefTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="PartySubTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="FixedRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistinctPartySchemaType", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML", propOrder = {
    "comment",
    "profile"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class DistinctPartySchemaType {

    @XmlElement(name = "Comment", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<Comment> comment;
    @XmlElement(name = "Profile", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<DistinctPartySchemaType.Profile> profile;
    @XmlAttribute(name = "FixedRef", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String fixedRef;
    @XmlAttribute(name = "DeltaAction")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected DeltaActionSchemaType deltaAction;

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comment }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<Comment> getComment() {
        if (comment == null) {
            comment = new ArrayList<Comment>();
        }
        return this.comment;
    }

    /**
     * Gets the value of the profile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DistinctPartySchemaType.Profile }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<DistinctPartySchemaType.Profile> getProfile() {
        if (profile == null) {
            profile = new ArrayList<DistinctPartySchemaType.Profile>();
        }
        return this.profile;
    }

    /**
     * Gets the value of the fixedRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getFixedRef() {
        return fixedRef;
    }

    /**
     * Sets the value of the fixedRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setFixedRef(String value) {
        this.fixedRef = value;
    }

    /**
     * Gets the value of the deltaAction property.
     * 
     * @return
     *     possible object is
     *     {@link DeltaActionSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Sets the value of the deltaAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeltaActionSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDeltaAction(DeltaActionSchemaType value) {
        this.deltaAction = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}Comment" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Identity" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}IdentitySchemaType" maxOccurs="unbounded"/>
     *         &lt;element name="Feature" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}FeatureSchemaType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="SanctionsEntryReference" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ExternalReference" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}Comment" minOccurs="0"/>
     *                   &lt;element name="ExRefValue" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DirectURL" minOccurs="0"/>
     *                   &lt;element name="SubLink" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Description" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DirectURL"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="TargetTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                           &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="ExRefTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                 &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="PartySubTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "comment",
        "identity",
        "feature",
        "sanctionsEntryReference",
        "externalReference"
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public static class Profile {

        @XmlElement(name = "Comment", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected List<Comment> comment;
        @XmlElement(name = "Identity", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML", required = true)
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected List<IdentitySchemaType> identity;
        @XmlElement(name = "Feature", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected List<FeatureSchemaType> feature;
        @XmlElement(name = "SanctionsEntryReference", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected List<DistinctPartySchemaType.Profile.SanctionsEntryReference> sanctionsEntryReference;
        @XmlElement(name = "ExternalReference", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected List<DistinctPartySchemaType.Profile.ExternalReference> externalReference;
        @XmlAttribute(name = "ID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected BigInteger id;
        @XmlAttribute(name = "PartySubTypeID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected BigInteger partySubTypeID;
        @XmlAttribute(name = "DeltaAction")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        protected DeltaActionSchemaType deltaAction;

        /**
         * Gets the value of the comment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Comment }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public List<Comment> getComment() {
            if (comment == null) {
                comment = new ArrayList<Comment>();
            }
            return this.comment;
        }

        /**
         * Gets the value of the identity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the identity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIdentity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IdentitySchemaType }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public List<IdentitySchemaType> getIdentity() {
            if (identity == null) {
                identity = new ArrayList<IdentitySchemaType>();
            }
            return this.identity;
        }

        /**
         * Gets the value of the feature property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the feature property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeature().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureSchemaType }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public List<FeatureSchemaType> getFeature() {
            if (feature == null) {
                feature = new ArrayList<FeatureSchemaType>();
            }
            return this.feature;
        }

        /**
         * Gets the value of the sanctionsEntryReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sanctionsEntryReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSanctionsEntryReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DistinctPartySchemaType.Profile.SanctionsEntryReference }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public List<DistinctPartySchemaType.Profile.SanctionsEntryReference> getSanctionsEntryReference() {
            if (sanctionsEntryReference == null) {
                sanctionsEntryReference = new ArrayList<DistinctPartySchemaType.Profile.SanctionsEntryReference>();
            }
            return this.sanctionsEntryReference;
        }

        /**
         * Gets the value of the externalReference property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the externalReference property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExternalReference().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DistinctPartySchemaType.Profile.ExternalReference }
         * 
         * 
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public List<DistinctPartySchemaType.Profile.ExternalReference> getExternalReference() {
            if (externalReference == null) {
                externalReference = new ArrayList<DistinctPartySchemaType.Profile.ExternalReference>();
            }
            return this.externalReference;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public BigInteger getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setID(BigInteger value) {
            this.id = value;
        }

        /**
         * Gets the value of the partySubTypeID property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public BigInteger getPartySubTypeID() {
            return partySubTypeID;
        }

        /**
         * Sets the value of the partySubTypeID property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setPartySubTypeID(BigInteger value) {
            this.partySubTypeID = value;
        }

        /**
         * Gets the value of the deltaAction property.
         * 
         * @return
         *     possible object is
         *     {@link DeltaActionSchemaType }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public DeltaActionSchemaType getDeltaAction() {
            return deltaAction;
        }

        /**
         * Sets the value of the deltaAction property.
         * 
         * @param value
         *     allowed object is
         *     {@link DeltaActionSchemaType }
         *     
         */
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public void setDeltaAction(DeltaActionSchemaType value) {
            this.deltaAction = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}Comment" minOccurs="0"/>
         *         &lt;element name="ExRefValue" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DirectURL" minOccurs="0"/>
         *         &lt;element name="SubLink" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Description" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DirectURL"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="TargetTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *                 &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="ExRefTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "comment",
            "exRefValue",
            "directURL",
            "subLink"
        })
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public static class ExternalReference {

            @XmlElement(name = "Comment", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected Comment comment;
            @XmlElement(name = "ExRefValue", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected DistinctPartySchemaType.Profile.ExternalReference.ExRefValue exRefValue;
            @XmlElement(name = "DirectURL", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected DirectURL directURL;
            @XmlElement(name = "SubLink", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected List<DistinctPartySchemaType.Profile.ExternalReference.SubLink> subLink;
            @XmlAttribute(name = "ExRefTypeID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected BigInteger exRefTypeID;
            @XmlAttribute(name = "DeltaAction")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected DeltaActionSchemaType deltaAction;

            /**
             * Gets the value of the comment property.
             * 
             * @return
             *     possible object is
             *     {@link Comment }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public Comment getComment() {
                return comment;
            }

            /**
             * Sets the value of the comment property.
             * 
             * @param value
             *     allowed object is
             *     {@link Comment }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setComment(Comment value) {
                this.comment = value;
            }

            /**
             * Gets the value of the exRefValue property.
             * 
             * @return
             *     possible object is
             *     {@link DistinctPartySchemaType.Profile.ExternalReference.ExRefValue }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public DistinctPartySchemaType.Profile.ExternalReference.ExRefValue getExRefValue() {
                return exRefValue;
            }

            /**
             * Sets the value of the exRefValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link DistinctPartySchemaType.Profile.ExternalReference.ExRefValue }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setExRefValue(DistinctPartySchemaType.Profile.ExternalReference.ExRefValue value) {
                this.exRefValue = value;
            }

            /**
             * Gets the value of the directURL property.
             * 
             * @return
             *     possible object is
             *     {@link DirectURL }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public DirectURL getDirectURL() {
                return directURL;
            }

            /**
             * Sets the value of the directURL property.
             * 
             * @param value
             *     allowed object is
             *     {@link DirectURL }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setDirectURL(DirectURL value) {
                this.directURL = value;
            }

            /**
             * Gets the value of the subLink property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the subLink property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSubLink().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DistinctPartySchemaType.Profile.ExternalReference.SubLink }
             * 
             * 
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public List<DistinctPartySchemaType.Profile.ExternalReference.SubLink> getSubLink() {
                if (subLink == null) {
                    subLink = new ArrayList<DistinctPartySchemaType.Profile.ExternalReference.SubLink>();
                }
                return this.subLink;
            }

            /**
             * Gets the value of the exRefTypeID property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public BigInteger getExRefTypeID() {
                return exRefTypeID;
            }

            /**
             * Sets the value of the exRefTypeID property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setExRefTypeID(BigInteger value) {
                this.exRefTypeID = value;
            }

            /**
             * Gets the value of the deltaAction property.
             * 
             * @return
             *     possible object is
             *     {@link DeltaActionSchemaType }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public DeltaActionSchemaType getDeltaAction() {
                return deltaAction;
            }

            /**
             * Sets the value of the deltaAction property.
             * 
             * @param value
             *     allowed object is
             *     {@link DeltaActionSchemaType }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setDeltaAction(DeltaActionSchemaType value) {
                this.deltaAction = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public static class ExRefValue {

                @XmlValue
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                protected String value;
                @XmlAttribute(name = "DeltaAction")
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                protected DeltaActionSchemaType deltaAction;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the deltaAction property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DeltaActionSchemaType }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public DeltaActionSchemaType getDeltaAction() {
                    return deltaAction;
                }

                /**
                 * Sets the value of the deltaAction property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DeltaActionSchemaType }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public void setDeltaAction(DeltaActionSchemaType value) {
                    this.deltaAction = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Description" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DirectURL"/>
             *       &lt;/sequence>
             *       &lt;attribute name="TargetTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
             *       &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "description",
                "directURL"
            })
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public static class SubLink {

                @XmlElement(name = "Description", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                protected DistinctPartySchemaType.Profile.ExternalReference.SubLink.Description description;
                @XmlElement(name = "DirectURL", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML", required = true)
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                protected DirectURL directURL;
                @XmlAttribute(name = "TargetTypeID", required = true)
                @XmlSchemaType(name = "nonNegativeInteger")
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                protected BigInteger targetTypeID;
                @XmlAttribute(name = "DeltaAction")
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                protected DeltaActionSchemaType deltaAction;

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DistinctPartySchemaType.Profile.ExternalReference.SubLink.Description }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public DistinctPartySchemaType.Profile.ExternalReference.SubLink.Description getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DistinctPartySchemaType.Profile.ExternalReference.SubLink.Description }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public void setDescription(DistinctPartySchemaType.Profile.ExternalReference.SubLink.Description value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the directURL property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DirectURL }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public DirectURL getDirectURL() {
                    return directURL;
                }

                /**
                 * Sets the value of the directURL property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DirectURL }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public void setDirectURL(DirectURL value) {
                    this.directURL = value;
                }

                /**
                 * Gets the value of the targetTypeID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public BigInteger getTargetTypeID() {
                    return targetTypeID;
                }

                /**
                 * Sets the value of the targetTypeID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public void setTargetTypeID(BigInteger value) {
                    this.targetTypeID = value;
                }

                /**
                 * Gets the value of the deltaAction property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DeltaActionSchemaType }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public DeltaActionSchemaType getDeltaAction() {
                    return deltaAction;
                }

                /**
                 * Sets the value of the deltaAction property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DeltaActionSchemaType }
                 *     
                 */
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public void setDeltaAction(DeltaActionSchemaType value) {
                    this.deltaAction = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                public static class Description {

                    @XmlValue
                    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                    protected String value;
                    @XmlAttribute(name = "DeltaAction")
                    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                    protected DeltaActionSchemaType deltaAction;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the deltaAction property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link DeltaActionSchemaType }
                     *     
                     */
                    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                    public DeltaActionSchemaType getDeltaAction() {
                        return deltaAction;
                    }

                    /**
                     * Sets the value of the deltaAction property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link DeltaActionSchemaType }
                     *     
                     */
                    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
                    public void setDeltaAction(DeltaActionSchemaType value) {
                        this.deltaAction = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *       &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
        public static class SanctionsEntryReference {

            @XmlAttribute(name = "SanctionsEntryID", required = true)
            @XmlSchemaType(name = "nonNegativeInteger")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected BigInteger sanctionsEntryID;
            @XmlAttribute(name = "DeltaAction")
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            protected DeltaActionSchemaType deltaAction;

            /**
             * Gets the value of the sanctionsEntryID property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public BigInteger getSanctionsEntryID() {
                return sanctionsEntryID;
            }

            /**
             * Sets the value of the sanctionsEntryID property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setSanctionsEntryID(BigInteger value) {
                this.sanctionsEntryID = value;
            }

            /**
             * Gets the value of the deltaAction property.
             * 
             * @return
             *     possible object is
             *     {@link DeltaActionSchemaType }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public DeltaActionSchemaType getDeltaAction() {
                return deltaAction;
            }

            /**
             * Sets the value of the deltaAction property.
             * 
             * @param value
             *     allowed object is
             *     {@link DeltaActionSchemaType }
             *     
             */
            @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
            public void setDeltaAction(DeltaActionSchemaType value) {
                this.deltaAction = value;
            }

        }

    }

}
