//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.17 at 11:26:16 AM CEST 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.ofac.tags;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntryDeltaFlagSchemaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EntryDeltaFlagSchemaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NewEntry"/>
 *     &lt;enumeration value="DeletedEntry"/>
 *     &lt;enumeration value="ModifiedEntry"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EntryDeltaFlagSchemaType", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
@XmlEnum
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public enum EntryDeltaFlagSchemaType {

    @XmlEnumValue("NewEntry")
    NEW_ENTRY("NewEntry"),
    @XmlEnumValue("DeletedEntry")
    DELETED_ENTRY("DeletedEntry"),
    @XmlEnumValue("ModifiedEntry")
    MODIFIED_ENTRY("ModifiedEntry");
    private final String value;

    EntryDeltaFlagSchemaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EntryDeltaFlagSchemaType fromValue(String v) {
        for (EntryDeltaFlagSchemaType c: EntryDeltaFlagSchemaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
