//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.17 at 11:26:16 AM CEST 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.ofac.tags;

import java.math.BigInteger;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ProfileRelationshipID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ProfileRelationshipReference", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class ProfileRelationshipReference {

    @XmlAttribute(name = "ProfileRelationshipID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected BigInteger profileRelationshipID;
    @XmlAttribute(name = "DeltaAction")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected DeltaActionSchemaType deltaAction;

    /**
     * Gets the value of the profileRelationshipID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public BigInteger getProfileRelationshipID() {
        return profileRelationshipID;
    }

    /**
     * Sets the value of the profileRelationshipID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setProfileRelationshipID(BigInteger value) {
        this.profileRelationshipID = value;
    }

    /**
     * Gets the value of the deltaAction property.
     * 
     * @return
     *     possible object is
     *     {@link DeltaActionSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Sets the value of the deltaAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeltaActionSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDeltaAction(DeltaActionSchemaType value) {
        this.deltaAction = value;
    }

}
