//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.17 at 11:26:16 AM CEST 
//


package com.generalbytes.batm.server.extensions.extra.watchlists.ofac.tags;

import java.math.BigInteger;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SanctionsEntryLinkSchemaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SanctionsEntryLinkSchemaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}Comment" minOccurs="0"/>
 *         &lt;element name="Date" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DateSchemaType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="EntryA-SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="EntryB-SanctionsEntryID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="EntryLinkTypeID" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="DeltaAction" type="{https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML}DeltaActionSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SanctionsEntryLinkSchemaType", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML", propOrder = {
    "comment",
    "date"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class SanctionsEntryLinkSchemaType {

    @XmlElement(name = "Comment", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Comment comment;
    @XmlElement(name = "Date", namespace = "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/ADVANCED_XML", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected DateSchemaType date;
    @XmlAttribute(name = "ID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected BigInteger id;
    @XmlAttribute(name = "EntryA-SanctionsEntryID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected BigInteger entryASanctionsEntryID;
    @XmlAttribute(name = "EntryB-SanctionsEntryID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected BigInteger entryBSanctionsEntryID;
    @XmlAttribute(name = "EntryLinkTypeID", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected BigInteger entryLinkTypeID;
    @XmlAttribute(name = "DeltaAction")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected DeltaActionSchemaType deltaAction;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link DateSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public DateSchemaType getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDate(DateSchemaType value) {
        this.date = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the entryASanctionsEntryID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public BigInteger getEntryASanctionsEntryID() {
        return entryASanctionsEntryID;
    }

    /**
     * Sets the value of the entryASanctionsEntryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setEntryASanctionsEntryID(BigInteger value) {
        this.entryASanctionsEntryID = value;
    }

    /**
     * Gets the value of the entryBSanctionsEntryID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public BigInteger getEntryBSanctionsEntryID() {
        return entryBSanctionsEntryID;
    }

    /**
     * Sets the value of the entryBSanctionsEntryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setEntryBSanctionsEntryID(BigInteger value) {
        this.entryBSanctionsEntryID = value;
    }

    /**
     * Gets the value of the entryLinkTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public BigInteger getEntryLinkTypeID() {
        return entryLinkTypeID;
    }

    /**
     * Sets the value of the entryLinkTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setEntryLinkTypeID(BigInteger value) {
        this.entryLinkTypeID = value;
    }

    /**
     * Gets the value of the deltaAction property.
     * 
     * @return
     *     possible object is
     *     {@link DeltaActionSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public DeltaActionSchemaType getDeltaAction() {
        return deltaAction;
    }

    /**
     * Sets the value of the deltaAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeltaActionSchemaType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2024-06-17T11:26:16+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDeltaAction(DeltaActionSchemaType value) {
        this.deltaAction = value;
    }

}
