/*************************************************************************************
 * Copyright (C) 2014-2016 GENERAL BYTES s.r.o. All rights reserved.
 *
 * This software may be distributed and modified under the terms of the GNU
 * General Public License version 2 (GPL2) as published by the Free Software
 * Foundation and appearing in the file GPL2.TXT included in the packaging of
 * this file. Please note that GPL2 Section 2[b] requires that all works based
 * on this software must also be made publicly available under the terms of
 * the GPL2 ("Copyleft").
 *
 * Contact information
 * -------------------
 *
 * GENERAL BYTES s.r.o.
 * Web      :  http://www.generalbytes.com
 *
 ************************************************************************************/
package com.generalbytes.batm.server.extensions.payment;

import java.math.BigDecimal;
import java.util.List;

/**
 * Payment specification is generated by server before asks @{@link IPaymentSupport } to create @{@link PaymentRequest}
 */
public interface IPaymentRequestSpecification {
    String getCryptoCurrency();
    String getDescription();

    void addOutput(String address, BigDecimal amount);
    List<IPaymentOutput> getOutputs();
    BigDecimal getTotal();

    long getValidInSeconds();
    String getTimeoutRefundAddress();
    void setTimeoutRefundAddress(String newRefundAddress);

    BigDecimal getOptimalMiningFee(BigDecimal feeCalculated, int transactionSize);
    void removeTotalAmountFromOutputs(BigDecimal totalAmountToRemove);
    int getRemoveAfterNumberOfConfirmationsOfOutgoingTransaction();
    int getRemoveAfterNumberOfConfirmationsOfIncomingTransaction();
    boolean isDoNotForward();
    boolean isZeroFixedFee();
    void optimize();
}
